# Generated by Django 4.2.20 on 2025-03-20 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_escolar_api', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
